### ISSUE TITLE
Round minutes to nearest integer

### ISSUE THREAD

**Issue by kelegorm** [orlv/ibreaktime#2]
Думаю, было бы лучше округлять минты до ближайшего целого. Чтобы при старте мы видели 25 минут вначале, а не 24. А в конце чтобы не видели 0 минут.

И 0 минут лучше вообще писать как Less than minute. Или как там попроще.

**Comment by orlv** [comment]
Ты имеешь в виду округлять в большую сторону? Да, можно сделать.

**Comment by kelegorm** [comment]
в большую, или в ближайшую. Но не в меньшую.

**Comment by orlv** [comment]
Done
