### ISSUE TITLE
Сброс циклов

### ISSUE THREAD

**Issue by kelegorm** [orlv/ibreaktime#3]
Было бы здорово иметь кнопку сброса насчитанных циклов. А то они считаются с момента запуска программы. 

И лучше иметь настройку, чтобы можно было назначить время автоматического сброса, например, 5 утра.

Или даже кнопка - сохранять количество циклов, если программа была перезапущена. Например, если я перезагрузил комп, то чтобы количество циклов сохранилось.

**Comment by orlv** [comment]
Кнопка сброса циклов есть, просто нажми на пункт меню с количеством циклов. Запоминание при перезапуске добавлю.
Предлагаю сделать автоматический сброс количества циклов после большого перерыва (например, 5 часов). 

Что скажешь?

**Comment by orlv** [comment]
Done.
