### ISSUE TITLE
Фича: удельные помидорки

### ISSUE THREAD

**Issue by kelegorm** [orlv/ibreaktime#5]
Считать примерное количество помидорок (25-минутных) с учетом того, что некоторые помидорки могли быть очень длинные и могли быть размером с несколько помидорок.

Например, я поработал два раза: 50 минут и 25 минут. И пусть показывать, что 3 помидорки отработано.

**Comment by orlv** [comment]
Предлагаю сделать так:  делить время работы на заданную продолжительность цикла, и округлять полученное значение.
Если цикл должен длиться 25 минут, а продлился 50, засчитается 2 цикла. Если продлился 70 - засчитается 3 цикла. 

Идёт?

**Comment by orlv** [comment]
Сделал, но немного иначе: отображается общее время работы, для него считается среднее количество циклов.
