### ISSUE TITLE
Неполные помидорки

### ISSUE THREAD

**Issue by kelegorm** [orlv/ibreaktime#6]
Что делать, если на серединке помидорки случился перерыв на более 5 минут? Сбросить помидорку, сохранив ее как не полную, или после возвращения продолжить ее отсчет? или вообще не останавливать отсчет?

**Comment by orlv** [comment]
Четвертый вариант — при возвращении таймер начинает отсчёт заново

**Comment by orlv** [comment]
Можно изменить :-)
